import * as w from './wmo.js'
console.log('wmo 模块加载 OK')
console.log('  describe(0)   ->', JSON.stringify(w.describe(0)))
console.log('  describe(65)  ->', JSON.stringify(w.describe(65)))
console.log('  describe(999) ->', JSON.stringify(w.describe(999)))
console.log('  icon(0,1)  晴/昼   ->', JSON.stringify(w.icon(0,1)))
console.log('  icon(0,0)  晴/夜   ->', JSON.stringify(w.icon(0,0)))
console.log('  icon(95,1) 雷阵雨  ->', JSON.stringify(w.icon(95,1)))
console.log('  icon(71,1) 小雪    ->', JSON.stringify(w.icon(71,1)))
console.log('  iconFromKind(cloud,1)    ->', JSON.stringify(w.iconFromKind('cloud',1)))
console.log('  iconFromKind(overcast,1) ->', JSON.stringify(w.iconFromKind('overcast',1)))
console.log('  iconFromKind(suncloud,1) ->', JSON.stringify(w.iconFromKind('suncloud',1)))
console.log('  kindFromCnText 多云   ->', w.kindFromCnText('多云'))
console.log('  kindFromCnText 雷阵雨 ->', w.kindFromCnText('雷阵雨'))
console.log('  kindFromCnText 雨夹雪 ->', w.kindFromCnText('雨夹雪'))
console.log('  kindFromCnText 沙尘暴 ->', w.kindFromCnText('沙尘暴'), '(未收录词，回落 cloud)')
